# Generated by Django 2.2.6 on 2020-04-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('date_planed', models.DateField()),
                ('date_deadline', models.DateField()),
                ('instagram', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('np_department', models.IntegerField()),
                ('is_payed', models.BooleanField(default=False)),
                ('date_payed', models.DateField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('date_sent', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('is_ready', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='products.Product')),
            ],
            options={
                'ordering': ['product'],
                'unique_together': {('order', 'product')},
            },
        ),
    ]
