# Generated by Django 3.0.5 on 2020-09-20 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('date_planed', models.DateField()),
                ('date_deadline', models.DateField(blank=True, null=True)),
                ('instagram', models.CharField(max_length=30)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('np_department', models.IntegerField(blank=True, null=True)),
                ('is_payed', models.BooleanField(default=False)),
                ('date_payed', models.DateField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('date_sent', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_planed'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('is_ready', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', related_query_name='orderitem', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='products.Product')),
            ],
            options={
                'ordering': ['product'],
            },
        ),
    ]
