# Generated by Django 3.0.5 on 2020-09-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200830_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_planed']},
        ),
    ]
