# Generated by Django 3.0.5 on 2020-09-06 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200902_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
