# Generated by Django 3.0.5 on 2020-09-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20200902_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='expenses',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
