# Generated by Django 3.0.5 on 2020-09-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20200902_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-date', '-created']},
        ),
    ]
